blank_issue_enabled: false
contact_links:
  - name: Security vulnerabilities
    url: mailto:admin@playlegend.net
    about: Please contact us if you have found a security vulnerability or have security concerns of any kind
